# Serverless Docs: docs.serverless.com
service: twitter-count-api

frameworkVersion: ">=1.67.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  profile: citibeats-universe
  environment:
    ACCOUNT_TYPE: enterprise
    API_ENDPOINT: https://vqw2vxw4bk.execute-api.eu-west-2.amazonaws.com/dev/counts
    ACCOUNT_USERNAME: twitterMockup2020
    ACCOUNT_PASSWORD: G74zxPTkEK
    QUERY_LENGTH: 2048
    QUERY_PREFIX: "-is:retweet "
  role: arn:aws:iam::337878073417:role/twitter-count-api-lambda
  cfnRole: arn:aws:iam::337878073417:role/twitter-count-api-cloudformation
functions:
  count:
    handler: src/handler.counts
    timeout: 30
    events:
      - http:
          path: count
          method: post
          cors: false

plugins:
  - serverless-python-requirements

package:
  exclude:
    - env/**
    - .vscode/**